### ISSUE TITLE
Using retractable markers

### ISSUE THREAD

**Issue by Diterex** [Sakati84/3DPrintColorizer#14]
It would be nice not to have to worry about the heat making the markers dry out. A multi-colored less overkill version of https://www.youtube.com/watch?v=c3LhK2SAusk&t=4s would be amazing.  Also check out https://www.youtube.com/watch?v=lcOcetpHhTU.

**Comment by Sakati84** [comment]
Hi, Sorry but i will definitely not do anything involving electronics here. I build quite some robots and have experience in this field. I just don´t think whatever come out of it would be widely used because of the costs and efforts need to rebuild something like this.
