### ISSUE TITLE
Outer wall only colorizing

### ISSUE THREAD

**Issue by ssilverm** [Sakati84/3DPrintColorizer#18]
Would there be a way to only have the PenColorizer plugin generate gcode that colors the outer edges of the models?

I had an issue printing a dual extrusion Pikachu where because the sharpie colored in the whole tail layer the print separated.

![image](https://user-images.githubusercontent.com/1273237/127939711-344035e8-8583-4d9b-8901-50c4f430da0a.png)

**Comment by Pineapplecake** [comment]
The setting `Infill > Infill Extruder` in CURA can be used to print all infill with Extruder 1, i.e. without colorizing.

**Comment by Sakati84** [comment]
Unfortunatly no. You could set the top/bottom Extruder to 1 but than you would have no color there. To solve this you could: reduce the top/bottom speed or print it larger or change the model so it interlocks at this position

**Comment by ssilverm** [comment]
Thanks!
