### ISSUE TITLE
Variable Name-Description Discrepancy: FirstPenYPosition

### ISSUE THREAD

**Issue by FlyMyPG** [Sakati84/3DPrintColorizer#2]
PenColorizer.py:48-54  The variable name does not match the description.

    "FirstPenYPosition":
    {
        "label": "First Pen Z Position",
        "description": "Z position for holding the first pen in the pen rack",
        "type": "float",
        "default_value": 238.0
    },

**Comment by Sakati84** [comment]
Fixed it
