### ISSUE TITLE
MARLIN BUGFIX2.0.X

### ISSUE THREAD

**Issue by scootr1975** [Sakati84/3DPrintColorizer#24]
I followed instructions and used the sample print. When I went to print it did not recognize the extruders. I use octoprint with my Ender 3 Pro. I have done several upgrades to the unit. I have the Creality 4.2.7 32bit board with direct drive extrusion. I have dual Z-axis. I have included some pictures Please help
<img width="933" alt="1" src="https://user-images.githubusercontent.com/45324570/128611939-9777d6b9-f0ef-48ca-b631-31f0aab46248.PNG">
<img width="246" alt="2" src="https://user-images.githubusercontent.com/45324570/128611941-d61c8012-c9c7-4278-ae2e-59fe1a567eb7.PNG">

**Comment by Sakati84** [comment]
Hm.. for some reasons he doesn’t like the T0 command. This should normally refer to your first and only extruder. Does it work directly via USB or SD-Card?

**Comment by stldenise** [comment]
I'm setting up an Ender 3 Pro also. I'm not a tech geek, so ignore if you did this: did you set up a new printer profile in OctoPrint with 7 nozzles? I was getting a similar error and they vanished when I set up a "new" printer.

**Comment by scootr1975** [comment]
No I did not. Thank you for the information. Did you check the share button
when you added the extra extruders or did you put in the offsets there.

**Comment by stldenise** [comment]
You know, it was late when I did that...didn't even see it! So, no I did not click shared nozzle or anything else.

**Comment by scootr1975** [comment]
Haha, thanks!

**Comment by scootr1975** [comment]
Awesome, thanks!
