### ISSUE TITLE
I can't turn on Infill first

### ISSUE THREAD

**Issue by Beanman122** [Sakati84/3DPrintColorizer#34]
I was thinking of how to make the quality better and I thought that it would help to turn on Infill before walls. Unfortunately, It turns out that you can't turn that on because the infill is using extruder 1 and the walls are not. If you turn the extruder settings for the infill to "not overridden" you are able to make this change. I don't know if this is possible but I was wondering if that setting would help and if there is a way that you could turn it on.

**Comment by Sakati84** [comment]
You can Set the infill Extruder to not overwritten. Infill is never colored. It's filtered out by the plugin.

**Comment by Beanman122** [comment]
oh, cool. Thanks so much
