### ISSUE TITLE
Putting a marker away and picking up the next one.

### ISSUE THREAD

**Issue by isaacBullinger** [Sakati84/3DPrintColorizer#47]
To save time later on in the print, when the holder goes up to put away a marker, it picks up the next one needed. It would need to start doing it at a higher layer, otherwise it would draw on the bed.

**Comment by Sparrowhawk120** [comment]
I don't think that would work though. For the same reason it would draw on the bed with too-low layer heights, the marker would smack into the print if it's bigger than the size of the print head.

**Comment by Sakati84** [comment]
I also think it would knock over the print.
