### ISSUE TITLE
Printing pen rack 

### ISSUE THREAD

**Issue by hfgd123** [Sakati84/3DPrintColorizer#70]
I wanted to print the pen rack, but the first layer was only printed partwise and the next layers (until I canceled the print) the hotend scratched over the lower layers. Everything else I try to print works well. So I thought maybe anyone here could help me. Heres a picture of what was intended to be the pen rack (printed with an Ender-3) :
![IMG_20210919_124548](https://user-images.githubusercontent.com/46094961/133924717-5ef3d09a-f971-4624-ab46-7b7a07d92a90.jpg)

**Comment by csanii123** [comment]
I haven't tried printing this model but it looks like your bed isn't level as the bottom right seems to have no brim/raft while the top does seem to have it intact. Suggest a relevel and use a skirt and see if that sticks well. If it does then move back to printing with a brim.

**Comment by hfgd123** [comment]
The problem with that: I leveled the bed a few minutes before I started printing this. And the first time I tried printing the pen rack (also with leveling right before), there was the same problem. But I'll try printing with a skirt next weekend

**Comment by csanii123** [comment]
Did you heat the bed/nozzle and then level ? When I 1st got my printer I wasn't doing that and prints were "ok" but the stick to the bed was hit and miss. Since I heated the bed/nozzle and then leveled...prints are much better and stick to the bed very well.

**Comment by hfgd123** [comment]
Bed and nozzle are always heated when I am leveling, yes

**Comment by hfgd123** [comment]
It worked now. thx
